import { CONNECTION_EXPIRED_ERROR_MESSAGE, DEVICE_NOT_CONNECTED_ERROR_MESSAGE } from "./constants";

export const DEVICE_NOT_CONNECTED_ERROR = new Error(DEVICE_NOT_CONNECTED_ERROR_MESSAGE);

export const CONNECTION_EXPIRED_ERROR = new Error(CONNECTION_EXPIRED_ERROR_MESSAGE);
